#!/usr/bin/env node
/**
 * Generates every resume page from resume/content.mjs.
 *
 * Six pages (two positionings x three languages) used to be six hand-edited
 * HTML files. Editing one meant editing six, which is how they drift.
 *
 *   node resume/generate.mjs
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DOCS } from './content.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

const TARGETS = {
  'main-en': 'resume/index.html',
  'main-zh-cn': 'resume/zh-cn/index.html',
  'main-zh-hk': 'resume/zh-hk/index.html',
  'caio-en': 'resume/caio/index.html',
  'caio-zh-cn': 'resume/caio/zh-cn/index.html',
  'caio-zh-hk': 'resume/caio/zh-hk/index.html',
};

const li = (x) => `<li>${x}</li>`;

const metrics = (d) => d.metrics
  .map((m) => `      <div class="metric"><strong>${m.value}</strong><span>${m.label}</span></div>`)
  .join('\n');

const whereHelp = (d) => !d.whereHelp ? '' : `
  <section class="where-help" aria-labelledby="where-help-title">
    <div class="shell">
      <p class="eyebrow" id="where-help-title">${d.whereHelp.eyebrow}</p>
      <div class="where-help-grid">
${d.whereHelp.items.map((x) => `        <article>
          <h3>${x.h3}</h3>
          <p>${x.p}</p>
        </article>`).join('\n')}
      </div>
    </div>
  </section>
`;

const practice = (d) => `
  <section class="agent-practice" aria-labelledby="agent-practice-title">
    <div class="shell">
      <div class="agent-practice-heading">
        <div>
          <p class="eyebrow">${d.practice.eyebrow}</p>
          <h2 id="agent-practice-title">${d.practice.title}</h2>
        </div>
        <p>${d.practice.intro}</p>
      </div>
      <div class="agent-practice-grid">
${d.practice.steps.map((s) => `        <article><span>${s.n}</span><h3>${s.h3}</h3><p>${s.p}</p><em class="practice-cost">${s.cost}</em></article>`).join('\n')}
      </div>
      <p class="agent-environment"><strong>${d.practice.envNowLabel}</strong><span>${d.practice.envNow}</span></p>
      <p class="agent-environment agent-environment-was"><strong>${d.practice.envWasLabel}</strong><span>${d.practice.envWas}</span></p>
    </div>
  </section>
`;

const experience = (d) => `      <section class="section" aria-labelledby="experience-title">
        <h2 class="section-title" id="experience-title">${d.experience.title}</h2>
        <ol class="timeline">
${d.experience.roles.map((r) => `          <li class="role">
            <div class="role-time">${r.time}<span>${r.place}</span></div>
            <div class="role-body">
              <h3>${r.title}</h3>
              <p class="company">${r.company}</p>${r.lead ? `\n              <p>${r.lead}</p>` : ''}
              <ul>
${r.bullets.map((b) => `                ${li(b)}`).join('\n')}
              </ul>
            </div>
          </li>`).join('\n')}
        </ol>
      </section>`;

const tradeoff = (d) => `      <section class="section" aria-labelledby="tradeoff-title">
        <h2 class="section-title" id="tradeoff-title">${d.tradeoff.title}</h2>
        <p class="tradeoff-intro">${d.tradeoff.intro}</p>
${d.tradeoff.groups.map((g) => `        <p class="tradeoff-group">${g.label}</p>
        <div class="tradeoff-list">
${g.items.map((x) => `          <article class="tradeoff">
            <h3>${x.h3}</h3>
            <p>${x.p}</p>
          </article>`).join('\n')}
        </div>${g.thread ? `\n        <p class="tradeoff-thread">${g.thread}</p>` : ''}`).join('\n')}
      </section>`;

const work = (d) => `      <section class="section" aria-labelledby="work-title">
        <h2 class="section-title" id="work-title">${d.work.title}</h2>
        <div class="project-list">
${d.work.projects.map((p) => `          <article class="project">
            <h3>${p.h3}</h3>
            <span class="project-tag">${p.tag}</span>
            <p>${p.p}</p>
          </article>`).join('\n')}
        </div>
      </section>`;

const skills = (sec, anchor) => `      <section class="section" aria-labelledby="${anchor}">
        <h2 class="section-title" id="${anchor}">${sec.title}</h2>
${sec.groups.map((g) => `        <div class="skill-group">${g.h3 ? `\n          <h3>${g.h3}</h3>` : ''}
          <p>${g.p}</p>
        </div>`).join('\n')}
      </section>`;

const media = (d) => `      <section class="section" aria-labelledby="recognition-title">
        <h2 class="section-title" id="recognition-title">${d.media.title}</h2>
        <div class="recognition-list">
${d.media.items.map((m) => `          <div><a ${m.link}</a><p>${m.p}</p></div>`).join('\n')}
        </div>
      </section>`;

function render(d) {
  return `<!doctype html>
<!-- Generated by resume/generate.mjs from resume/content.mjs. Do not edit by hand. -->
<html lang="${d.lang}">
<head>
${d.head}
</head>
<body>
  <nav class="topbar" aria-label="Resume controls">
    <div class="shell topbar-inner">
      <a class="home-link" href="/">${d.home}</a>
      <div class="toolbar">
        <div class="language-switcher" aria-label="Language">
${d.langs.map((l) => `          <a href="${l.href}" lang="${l.lang}"${l.current ? ' aria-current="page"' : ''}>${l.label}</a>`).join('\n')}
        </div>
        <button class="print-button" type="button" data-print>${d.print}</button>
      </div>
    </div>
  </nav>

  <header class="resume-header">
    <div class="shell identity">
      <img class="portrait" src="${d.portrait}" width="120" height="120" alt="${d.portraitAlt}" fetchpriority="high">
      <div>
        <p class="eyebrow">${d.eyebrow}</p>
        <h1>${d.name}</h1>
        <p class="headline">${d.headline}</p>
        <p class="location">${d.location}</p>${d.availability ? `\n        <p class="availability">${d.availability}</p>` : ''}
      </div>
      <ul class="contact-list" aria-label="Contact links">
${d.contacts.map((c) => `        ${li(c)}`).join('\n')}
      </ul>
    </div>
  </header>

  <div class="shell intro-grid">
    <p class="summary-lead">${d.summaryLead}</p>
    <p class="summary">${d.summary}</p>
    <div class="impact-grid" aria-label="Career highlights">
${metrics(d)}
    </div>
  </div>
${whereHelp(d)}${practice(d)}
  <main class="shell resume-main">
    <div>
${experience(d)}

${tradeoff(d)}

${work(d)}

    </div>

    <aside>
${skills(d.capabilities, 'capabilities-title')}

${skills(d.education, 'education-title')}

${skills(d.interests, 'interests-title')}

${media(d)}

    </aside>
  </main>

  <footer class="footer">
    <div class="shell footer-inner">
${d.footer.map((f) => `      <span>${f}</span>`).join('\n')}
    </div>
  </footer>
  <script src="${d.js}"></script>
</body>
</html>
`;
}

let n = 0;
for (const [key, target] of Object.entries(TARGETS)) {
  const doc = DOCS[key];
  if (!doc) throw new Error(`content.mjs has no entry for ${key}`);
  writeFileSync(join(ROOT, target), render(doc), 'utf8');
  console.log('wrote', target);
  n += 1;
}
console.log(`${n} pages generated from resume/content.mjs`);
